[package]
name = "cowbench"
version = "0.1.0"
authors = ["Thomas Bächler <thomas.baechler@gmx.de>"]
edition = "2018"

[dependencies]
rand = "0.7"
rand_chacha = "0.2"
jemallocator = { version = "0.3", optional = true }

[features]
jemalloc = ["jemallocator"]